### ISSUE TITLE
about Individual training

### ISSUE THREAD

**Issue by ZhangJiajun1995** [MediaBrain-SJTU/RegAD#13]
Dear author：
    I read the code. You build the support set and the query set as two views in Aggregated training. The number of support set is the shot. For Individual training, can you provide some details of the training？How to use the support set?

**Comment by chaoqinhuang** [comment]
Individual training is a naive baseline where we only use very few samples in the target category to train the registration model. All these training samples are from the support set for the target category. All you need to do is simply modify the dataloader. Individual training often becomes overfitting very quickly because there are very few training samples. We strongly suggest using the aggregated training version we released.
