### ISSUE TITLE
Worse performance when including test object in training

### ISSUE THREAD

**Issue by tommiekerssies** [MediaBrain-SJTU/RegAD#27]
When I include the test object in the training data, performance is actually worse. How could this be? I tested this with object pill in MVTec.

**Comment by chaoqinhuang** [comment]
We did not conduct the experiments in the setting you mentioned because it is not what this work focuses on. But I guess something went wrong for your experiments. Or I guess your training is overfitting or collapsing. I remember that pills in MVTec are all centered and have a similar orientation and thus easier to overfit. If you need more discussion you are welcome to email me.
