### ISSUE TITLE
where is the support dataset in MPDD dataset?

### ISSUE THREAD

**Issue by Holmes-GU** [MediaBrain-SJTU/RegAD#29]
Hi, there is a support_dataset.zip for MVTec. However, where is the corresponding one for the MPDD dataset?
Thank you.

**Comment by SarthakGarg19** [comment]
I had the same question. 
Also how can we create our own support dataset for custom data?

**Comment by chaoqinhuang** [comment]
Please follow #1 to generate the support set for MPDD or your custom dataset

**Comment by chaoqinhuang** [comment]
If there are no other problems I close this issue.

**Comment by nehaejaz** [comment]
Hi @chaoqinhuang 
Can you share the support set that you used for your MPDD results so that we can have a fair comparison between your method and others?

I created a support set for MPDD by randomly selected some images but it is giving lower results than mentioned in your paper. Therefore if you can share the support set for MPDD that you used like you did for MVTec it will be helpful for other researchers. 

Thank you
